*** Starting uWSGI 2.0.21 (64bit) on [Wed May 17 10:06:04 2023] ***
compiled with version: 9.4.0 on 17 May 2023 00:48:53
os: Linux-5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023
nodename: iZ0jl2weg4xzdux0ta5gn6Z
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /root/HyperMusic_backend/HyperMusic_backend
writing pidfile to /root/HyperMusic_backend/HyperMusic_backend/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/HyperMusic_backend/HyperMusic_backend
your processes number limit is 7287
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
Python main interpreter initialized at 0x556fccb638d0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031270 bytes (1007 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
/usr/local/lib/python3.8/dist-packages/django/db/models/base.py:366: RuntimeWarning: Model 'Message.posttocomment' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x556fccb638d0 pid: 101036 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 101036)
spawned uWSGI worker 1 (pid: 101040, cores: 2)
spawned uWSGI worker 2 (pid: 101041, cores: 2)
spawned uWSGI worker 3 (pid: 101043, cores: 2)
spawned uWSGI worker 4 (pid: 101044, cores: 2)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 101040)...
Gracefully killing worker 3 (pid: 101043)...
Gracefully killing worker 2 (pid: 101041)...
Gracefully killing worker 4 (pid: 101044)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/HyperMusic_backend/HyperMusic_backend
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 17 10:07:47 2023] ***
compiled with version: 9.4.0 on 17 May 2023 00:48:53
os: Linux-5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023
nodename: iZ0jl2weg4xzdux0ta5gn6Z
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /root/HyperMusic_backend/HyperMusic_backend
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/HyperMusic_backend/HyperMusic_backend
your processes number limit is 7287
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
Python main interpreter initialized at 0x556e3fdd4340
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031270 bytes (1007 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
/usr/local/lib/python3.8/dist-packages/django/db/models/base.py:366: RuntimeWarning: Model 'Message.posttocomment' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x556e3fdd4340 pid: 101036 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 101036)
spawned uWSGI worker 1 (pid: 101542, cores: 2)
spawned uWSGI worker 2 (pid: 101543, cores: 2)
spawned uWSGI worker 3 (pid: 101545, cores: 2)
spawned uWSGI worker 4 (pid: 101546, cores: 2)
Invalid HTTP_HOST header: '8.130.12.73'. You may need to add '8.130.12.73' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(message)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8.130.12.73'. You may need to add '8.130.12.73' to ALLOWED_HOSTS.
Bad Request: /api
WARNING:django.request:Bad Request: /api
[pid: 101546|app: 0|req: 1/1] 219.239.227.216 () {40 vars in 830 bytes} [Wed May 17 10:08:01 2023] GET /api => generated 58523 bytes in 133 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '8.130.12.73'. You may need to add '8.130.12.73' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(message)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8.130.12.73'. You may need to add '8.130.12.73' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '8.130.12.73'. You may need to add '8.130.12.73' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(message)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '8.130.12.73'. You may need to add '8.130.12.73' to ALLOWED_HOSTS.
Bad Request: /api
WARNING:django.request:Bad Request: /api
[pid: 101546|app: 0|req: 2/2] 61.151.231.107 () {36 vars in 637 bytes} [Wed May 17 10:12:01 2023] GET /api => generated 57966 bytes in 22 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 1)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 101542)...
Gracefully killing worker 3 (pid: 101545)...
Gracefully killing worker 2 (pid: 101543)...
Gracefully killing worker 4 (pid: 101546)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/HyperMusic_backend/HyperMusic_backend
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 17 10:12:52 2023] ***
compiled with version: 9.4.0 on 17 May 2023 00:48:53
os: Linux-5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023
nodename: iZ0jl2weg4xzdux0ta5gn6Z
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /root/HyperMusic_backend/HyperMusic_backend
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/HyperMusic_backend/HyperMusic_backend
your processes number limit is 7287
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
Python main interpreter initialized at 0x563829408340
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031270 bytes (1007 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
/usr/local/lib/python3.8/dist-packages/django/db/models/base.py:366: RuntimeWarning: Model 'Message.posttocomment' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x563829408340 pid: 101036 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 101036)
spawned uWSGI worker 1 (pid: 101749, cores: 2)
spawned uWSGI worker 2 (pid: 101750, cores: 2)
spawned uWSGI worker 3 (pid: 101752, cores: 2)
spawned uWSGI worker 4 (pid: 101753, cores: 2)
Not Found: /api
WARNING:django.request:Not Found: /api
[pid: 101753|app: 0|req: 1/1] 219.239.227.216 () {42 vars in 861 bytes} [Wed May 17 10:12:58 2023] GET /api => generated 2549 bytes in 109 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /api
WARNING:django.request:Not Found: /api
[pid: 101753|app: 0|req: 2/2] 1.202.122.101 () {42 vars in 998 bytes} [Wed May 17 10:23:00 2023] GET /api => generated 2549 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 1)
Not Found: /api
WARNING:django.request:Not Found: /api
[pid: 101753|app: 0|req: 3/3] 1.202.122.101 () {42 vars in 998 bytes} [Wed May 17 10:25:05 2023] GET /api => generated 2549 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /api
WARNING:django.request:Not Found: /api
[pid: 101753|app: 0|req: 4/4] 219.239.227.125 () {40 vars in 770 bytes} [Wed May 17 10:27:57 2023] GET /api => generated 2549 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 1)
Not Found: /api/music
WARNING:django.request:Not Found: /api/music
[pid: 101753|app: 0|req: 5/5] 219.239.227.125 () {36 vars in 475 bytes} [Wed May 17 10:28:49 2023] GET /api/music?id=1 => generated 2572 bytes in 6 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /api/music
WARNING:django.request:Not Found: /api/music
[pid: 101750|app: 0|req: 1/6] 219.239.227.125 () {36 vars in 466 bytes} [Wed May 17 10:29:23 2023] GET /api/music => generated 2567 bytes in 105 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
Not Found: /api
WARNING:django.request:Not Found: /api
[pid: 101753|app: 0|req: 6/7] 54.248.195.229 () {38 vars in 740 bytes} [Wed May 17 10:37:15 2023] GET /api => generated 2549 bytes in 5 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 15:33:16 2023] ***
compiled with version: 9.4.0 on 17 May 2023 00:48:53
os: Linux-5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023
nodename: iZ0jl2weg4xzdux0ta5gn6Z
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /root/HyperMusic_backend/HyperMusic_backend
writing pidfile to /root/HyperMusic_backend/HyperMusic_backend/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/HyperMusic_backend/HyperMusic_backend
your processes number limit is 7287
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
Python main interpreter initialized at 0x5585bfebd8e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031270 bytes (1007 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5585bfebd8e0 pid: 131327 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 131327)
spawned uWSGI worker 1 (pid: 131331, cores: 2)
spawned uWSGI worker 2 (pid: 131332, cores: 2)
spawned uWSGI worker 3 (pid: 131334, cores: 2)
spawned uWSGI worker 4 (pid: 131335, cores: 2)
[pid: 131332|app: 0|req: 1/1] 219.239.227.110 () {40 vars in 854 bytes} [Wed May 24 15:33:24 2023] GET /api/user/login/ => generated 64 bytes in 126 msecs (HTTP/1.1 200) 7 headers in 212 bytes (1 switches on core 0)
Not Found: /api/
WARNING:django.request:Not Found: /api/
[pid: 131331|app: 0|req: 1/2] 219.239.227.110 () {40 vars in 832 bytes} [Wed May 24 15:33:29 2023] GET /api/ => generated 2771 bytes in 107 msecs (HTTP/1.1 404) 7 headers in 229 bytes (1 switches on core 0)
[pid: 131334|app: 0|req: 1/3] 219.239.227.110 () {40 vars in 888 bytes} [Wed May 24 15:33:38 2023] GET /api/message/send_email_register/ => generated 64 bytes in 99 msecs (HTTP/1.1 200) 7 headers in 212 bytes (1 switches on core 0)
[pid: 131334|app: 0|req: 2/4] 219.239.227.148 () {46 vars in 840 bytes} [Wed May 24 15:34:24 2023] POST /api/message/send_email_register/ => generated 64 bytes in 8 msecs (HTTP/1.1 200) 9 headers in 304 bytes (1 switches on core 1)
Internal Server Error: /api/message/send_email_register/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/HyperMusic_backend/HyperMusic_backend/./Message/views.py", line 675, in send_email_register
    if send_sms_code(email, sms_code) == 1:
  File "/root/HyperMusic_backend/HyperMusic_backend/./Message/views.py", line 654, in send_sms_code
    send_status = send_mail(email_title, email_body, EMAIL_FROM, [to_email])
  File "/usr/local/lib/python3.8/dist-packages/django/core/mail/__init__.py", line 87, in send_mail
    return mail.send()
  File "/usr/local/lib/python3.8/dist-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.8/dist-packages/django/core/mail/backends/smtp.py", line 127, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.8/dist-packages/django/core/mail/backends/smtp.py", line 85, in open
    self.connection = self.connection_class(
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 341, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python3.8/smtplib.py", line 398, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
ERROR:django.request:Internal Server Error: /api/message/send_email_register/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/HyperMusic_backend/HyperMusic_backend/./Message/views.py", line 675, in send_email_register
    if send_sms_code(email, sms_code) == 1:
  File "/root/HyperMusic_backend/HyperMusic_backend/./Message/views.py", line 654, in send_sms_code
    send_status = send_mail(email_title, email_body, EMAIL_FROM, [to_email])
  File "/usr/local/lib/python3.8/dist-packages/django/core/mail/__init__.py", line 87, in send_mail
    return mail.send()
  File "/usr/local/lib/python3.8/dist-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.8/dist-packages/django/core/mail/backends/smtp.py", line 127, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.8/dist-packages/django/core/mail/backends/smtp.py", line 85, in open
    self.connection = self.connection_class(
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 341, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python3.8/smtplib.py", line 398, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
[pid: 131335|app: 0|req: 1/5] 219.239.227.110 () {40 vars in 723 bytes} [Wed May 24 15:34:49 2023] POST /api/message/send_email_register/ => generated 90005 bytes in 30253 msecs (HTTP/1.1 500) 7 headers in 250 bytes (1 switches on core 0)
[pid: 131335|app: 0|req: 2/6] 103.142.141.74 () {48 vars in 852 bytes} [Wed May 24 15:35:25 2023] OPTIONS /api/api/user/like_music/ => generated 0 bytes in 0 msecs (HTTP/1.1 200) 8 headers in 461 bytes (1 switches on core 1)
Not Found: /api/api/user/like_music/
WARNING:django.request:Not Found: /api/api/user/like_music/
[pid: 131335|app: 0|req: 3/7] 37.128.245.24 () {46 vars in 837 bytes} [Wed May 24 15:35:26 2023] POST /api/api/user/like_music/ => generated 2832 bytes in 6 msecs (HTTP/1.1 404) 9 headers in 323 bytes (1 switches on core 1)
Not Found: /api/api/user/like_music/
WARNING:django.request:Not Found: /api/api/user/like_music/
[pid: 131335|app: 0|req: 4/8] 50.114.59.22 () {46 vars in 837 bytes} [Wed May 24 15:35:27 2023] POST /api/api/user/like_music/ => generated 2832 bytes in 5 msecs (HTTP/1.1 404) 9 headers in 323 bytes (1 switches on core 1)
...gracefully killing workers...
Gracefully killing worker 2 (pid: 131332)...
Gracefully killing worker 1 (pid: 131331)...
Gracefully killing worker 4 (pid: 131335)...
Gracefully killing worker 3 (pid: 131334)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/HyperMusic_backend/HyperMusic_backend
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 15:38:41 2023] ***
compiled with version: 9.4.0 on 17 May 2023 00:48:53
os: Linux-5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023
nodename: iZ0jl2weg4xzdux0ta5gn6Z
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /root/HyperMusic_backend/HyperMusic_backend
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/HyperMusic_backend/HyperMusic_backend
your processes number limit is 7287
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
Python main interpreter initialized at 0x5640de8f4350
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031270 bytes (1007 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5640de8f4350 pid: 131327 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 131327)
spawned uWSGI worker 1 (pid: 132135, cores: 2)
spawned uWSGI worker 2 (pid: 132136, cores: 2)
spawned uWSGI worker 3 (pid: 132137, cores: 2)
spawned uWSGI worker 4 (pid: 132139, cores: 2)
